# Generated by Django 4.1.2 on 2022-10-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('inStock', models.IntegerField()),
            ],
            options={
                'ordering': ['name', 'price', 'inStock'],
            },
        ),
    ]
